version: '3'

services:
  concourse-db:
    image: postgres
    environment:
      POSTGRES_DB: concourse
      POSTGRES_PASSWORD: concourse_pass
      POSTGRES_USER: concourse_user
      PGDATA: /database

  concourse:
    image: concourse/concourse:7.3
    command: quickstart
    privileged: true
    depends_on: [concourse-db]
    ports: ["8080:8080"]
    environment:
      CONCOURSE_POSTGRES_HOST: concourse-db
      CONCOURSE_POSTGRES_USER: concourse_user
      CONCOURSE_POSTGRES_PASSWORD: concourse_pass
      CONCOURSE_POSTGRES_DATABASE: concourse
      CONCOURSE_EXTERNAL_URL: http://localhost:8080
      CONCOURSE_ADD_LOCAL_USER: test:test
      CONCOURSE_MAIN_TEAM_LOCAL_USER: test
      # overlay BAGGAGECLAIM_DRIVER does not work in linux when multiple tasks write to a dir
      CONCOURSE_WORKER_BAGGAGECLAIM_DRIVER: naive

      # CONCOURSE_CLIENT_SECRET: '...='
      # CONCOURSE_TSA_CLIENT_SECRET: '...='

  registry:
    image: registry:2
    ports: ["5000:5000"]
    restart: always

  smocker:
    image: thiht/smocker
    ports:
      - 8081:8081