language: python
python:
  - "3.5"
before_install:
  - pip install flake8
  - python -m flake8 .

  - pip install --upgrade setuptools
  - pip install --upgrade pip
  # Install the coverage utility and coveralls reporting utility
  - pip install pytest-cov
  - pip install coveralls
install:
  # Install test requirements
  - pip install -e ".[test]"
  # Now install it as a standalone distribution
  - pip uninstall -y .
  - pip install .
script:
  - py.test -v --cov-config .coveragerc --cov=nebu
after_success:
  - coverage report
  # Report test coverage to coveralls.io
  - coveralls
notifications:
  email: false
