# https://stackoverflow.com/a/65895910
name: Weekly Submodule Update

on:
  # push:
  #   branches: [ main ]
  schedule:
  - cron: '0 4 * * 0'

jobs:
  submodule-update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Update submodule
      run: ./install-submodules.sh --update
    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: Update submodules
        signoff: true
        branch: update-submodules
        delete-branch: true
        title: 'Update submodules'
