name: Docker build and test

# https://stackoverflow.com/a/67136237
on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2
      - name: Install graphviz and dot
        run: sudo apt-get install graphviz
      - name: Install submodules
        run: SKIP_SUBMODULE_UPGRADE=1 ./update-submodules.sh
      - name: Run Tests
        run: ./test.sh
