name: Docker build and test

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2
      - name: Install graphviz and dot
        run: sudo apt-get install graphviz
      - name: Run Tests
        run: ./test.sh
