name: Docker build and test

# https://stackoverflow.com/a/67136237
on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2
      - name: Install graphviz and dot
        run: sudo apt-get install graphviz
      - name: Install submodules
        run: SKIP_SUBMODULE_UPGRADE=1 ./update-submodules.sh
      - name: update visual dependency graphs
        run: CI_TEST=true ./test-step-00.sh
      - name: prepare directories
        run: CI_TEST=true ./test-step-01.sh
      - name: build container and run all-git-pdf
        run: CI_TEST=true ./test-step-02.sh
      - name: Run all-git-web
        run: CI_TEST=true ./test-step-03.sh
      - name: Run all-archive-web
        run: CI_TEST=true ./test-step-04.sh
      - name: Run all-archive-pdf
        run: CI_TEST=true ./test-step-05.sh
      - name: Run all-archive-gdoc
        run: CI_TEST=true ./test-step-06.sh
      - name: Run the last step of all-archive-gdoc (archive-convert-docx)
        run: CI_TEST=true ./test-step-07.sh
      - name: Collect coverage and upload
        run: CI_TEST=true ./test-step-08.sh
