name: Docker build and test

# https://stackoverflow.com/a/67136237
on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
      - name: Install graphviz and dot
        run: sudo apt-get install graphviz
      - name: Install submodules
        run: ./install-submodules.sh
      - name: update visual dependency graphs and verify typescript code builds concourse files and the step-config.json file
        run: CI_TEST=true ./test-step-00.bash
      - name: prepare directories and build container
        run: CI_TEST=true ./test-step-01.bash
      - name: Run all-git-pdf
        run: CI_TEST=true ./test-step-02.bash
      - name: Run all-git-web
        run: CI_TEST=true ./test-step-03.bash
      - name: Run all-archive-web
        run: CI_TEST=true ./test-step-04.bash
      - name: Run all-archive-pdf
        run: CI_TEST=true ./test-step-05.bash
      - name: Run all-archive-gdoc
        run: CI_TEST=true ./test-step-06.bash
      - name: Run the last step of all-archive-gdoc (archive-convert-docx)
        run: CI_TEST=true ./test-step-07.bash
      - name: Collect coverage and upload
        run: CI_TEST=true ./test-step-08.bash
